---
- name: Assure dir exist
  file: path=/etc/systemd/system/docker.service.d  state=directory

- name: systemd drop-in with our custom docker service
  template: src=flannel-network.conf.j2 dest=/etc/systemd/system/docker.service.d/flannel-network.conf mode=0644

- name: systmed reload
  command: /usr/bin/systemctl  daemon-reload
